spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos
    username: security
    password: security
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:             #configuração do security para apontar para a credencal que criei no google para fazer autenticação com o google#
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

# desabilitando as respostas genericas no swagger
springdoc:
  override-with-generic-response: false